title: "Nemo's Articles"
description: "Thoughts, stories, and ideas worth sharing"
url: "https://nemogotmad.github.io"
author: "Nemo Gotmad"
email: pragsnemo01@gmail.com
timezone: Asia/Kolkata

markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
      author: "Nemo Gotmad"
